Import tf-40a1.tar.gz

diff --git a/unix/tfconfig b/unix/tfconfig
--- a/unix/tfconfig
+++ b/unix/tfconfig
@@ -33,16 +33,16 @@ TFVERSION=`sed -n -e '/Fugue version/s/^.*"\(.*\)".*$/\1/p' ../src/main.c`
 
 echo "Configuring $TFVERSION"; echo
 
-rm -f ../src/Makefile a.out
-
 ### Initialize variables, just in case they're already defined.
 
+AOUT=a.out
 BINDIR=''
 # CC=''		;# Use the value from the environment if there is one.
 CCFLAGS=${TFDEV_CCFLAGS-'-O'}
 # CPP=''	;# Use the value from the environment if there is one.
+CYGWIN32=0
 DMALLOC="${TFDEV_DMALLOC}"
-EXE="${TFDEV_EXE}"
+TF="${TFDEV_TF}"
 FLAGS=''
 GNU_C=0
 LIBDIR="${TFDEV_LIBDIR}"
@@ -61,10 +61,25 @@ SYMLINK="${TFDEV_SYMLINK}"
 TERMINAL=''
 TFVER="$*"
 TTYDRIVER=''
-USE_FLOAT=''	;# incomplete
+X=''
 
 if [ -z "$USER" ]; then USER=$LOGNAME; fi
 export USER
+
+UNAME=`{ uname -s && uname -v && uname -r || uname -a; } 2>/dev/null`
+echo "#define UNAME     " \"$UNAME\" >&4
+case "$UNAME" in
+"SunOS 5.4")
+    echo "#define SUNOS_5_4" >&4
+    ;;
+"CYGWIN32"*)
+    TERMINAL="HARDCODE TERM_ansi"
+    AOUT="a.exe"
+    X=".exe"
+    TF="${TFDEV_TF}${X}"
+    CYGWIN32=1
+    ;;
+esac
 
 ### Read in user definitions.
 if [ -r ./Config ]; then . ./Config; fi
@@ -74,6 +89,7 @@ echo '#### This file was automatically generated by unix/tfconfig.' >&5
 echo '#### Any configuration changes should be made in unix/Config.' >&5
 echo >&5
 echo "TFVERSION  = \"${TFVERSION}\"" >&5
+echo "X          = ${X}" >&5
 echo "O          = o" >&5
 
 cat >&4 <<EOF
@@ -82,10 +98,6 @@ cat >&4 <<EOF
  */
 #define PLATFORM_UNIX
 EOF
-
-UNAME=`{ uname -s && uname -v && uname -r || uname -a; } 2>/dev/null`
-echo "#define UNAME     " \"$UNAME\" >&4
-[ "$UNAME" = "SunOS 5.4" ] && echo "#define SUNOS_5_4" >&4
 
 if [ -z "$QUIET" ] && echo $TFVERSION | egrep "alpha" >/dev/null 2>&1; then
 cat <<EOF
@@ -137,13 +149,13 @@ fi
 
 
 [ -z "$MODE" ]      && MODE=755
-[ -z "$EXE" ]       && EXE="${BINDIR}/tf"
+[ -z "$TF" ]        && TF="${BINDIR}/tf${X}"
 
 
 ### Sanity check for filenames (some people do pretty stupid things)
 # The "${SYMLINK}/" is just to make the grep return false if SYMLINK is empty.
 
-if echo "$EXE"         | egrep "^[^/]" >/dev/null 2>&1 ||
+if echo "$TF"          | egrep "^[^/]" >/dev/null 2>&1 ||
    echo "$LIBDIR"      | egrep "^[^/]" >/dev/null 2>&1 ||
    echo "${SYMLINK}/"  | egrep "^[^/]" >/dev/null 2>&1
 then
@@ -155,7 +167,7 @@ fi
 # Don't allow installation in the build tree (people have actually tried this).
 # The cd;pwd is needed to normalize the directory name in case of links, etc.
 
-DIR1=`echo $EXE     | sed 's;/[^/]*$;;'`
+DIR1=`echo $TF      | sed 's;/[^/]*$;;'`
 DIR1=`cd $DIR1 && pwd`
 DIR2=`echo $LIBDIR  | sed 's;/[^/]*$;;'`
 DIR2=`cd $DIR2 && pwd`
@@ -183,8 +195,8 @@ fi
 
 # Too many people have renamed the distribution directory to "$HOME/tf", and
 # then wondered why they couldn't install the executable as "$HOME/tf".
-if [ -d "${EXE}" ]; then
-    echo "\"${EXE}\" is a directory; you can not install the executable"
+if [ -d "${TF}" ]; then
+    echo "\"${TF}\" is a directory; you can not install the executable"
     echo 'with the same name.  Either rename the directory, or choose a'
     echo 'different name for the executable.'
     exit 1
@@ -193,7 +205,7 @@ fi
 
 ### Confirm.
 
-echo "TF binary will be installed as     $EXE"
+echo "TF binary will be installed as     $TF"
 if [ -n "$SYMLINK" ]; then
     echo "    with a symbolic link:          $SYMLINK"
 fi
@@ -224,11 +236,17 @@ while [ -z "$ans" ]; do
 done
 echo; echo
 
+rm -f ../src/Makefile ${AOUT}
+
 echo "#define LIBDIR     \"${LIBDIR}\"" >&4
-echo "#define MAILDIR    \"${MAILDIR}\"" >&4
+if [ -n "$MAILDIR" ]; then
+    echo "#define MAILDIR    \"${MAILDIR}\"" >&4
+else
+    echo "#undef  MAILDIR" >&4
+fi
 
 echo "MAKE       = ${MAKE}" >&5
-echo "EXE        = ${EXE}" >&5
+echo "TF         = ${TF}" >&5
 echo "SYMLINK    = ${SYMLINK}" >&5
 echo "LIBDIR     = ${LIBDIR}" >&5
 echo "MAILDIR    = ${MAILDIR}" >&5
@@ -301,10 +319,10 @@ elif egrep 'gnuc' test.out >/dev/null 2>&1; then
     echo "Ah ha, ${CC} is GNU C."
     GNU_C=1
 elif egrep 'stdc' test.out >/dev/null 2>&1; then
-    echo "Cool, you have a standard (ANSI) compiler."
+    echo "Cool, you appear have a standard (ANSI/ISO) compiler."
     STD_C=1
 else
-    echo "Your compiler doesn't appear to be standard (ANSI)."
+    echo "Your compiler doesn't appear to be standard (ANSI/ISO)."
 fi
 
 
@@ -391,7 +409,7 @@ if echo '#include <locale.h>' >test.c; ${CPP} test.c >/dev/null 2>&1; then
     echo "Found <locale.h>."
 else
     echo '#undef  LOCALE_H' >&4
-    echo "I can't find <locale.h>, but that's ok."
+    echo "I can't find <locale.h>; alternate locales will not be supported."
 fi
 
 
@@ -501,13 +519,20 @@ cat > symtest.c <<EOF
 #ifdef STDLIB_H
 # include STDLIB_H
 #endif
+#include <sys/types.h>
+#include <sys/socket.h>  /* for connect() */
+#ifdef NETDB_H
+# include NETDB_H  /* for gethostbyname(), h_errno */
+#endif
 #include STRING_H
 #include <math.h>
+#ifndef h_errno
+extern int h_errno;
+#endif
 
 int main() {
     int i;
     char *s;
-    extern int h_errno;
 
     bcopy(NULL, NULL, 0);
     bsearch((void*)NULL, (void*)NULL, 0, 0, NULL);
@@ -590,13 +615,19 @@ do
 done
 
 
+if [ "$CYGWIN32" = "1" ]; then
+    echo "#undef  HAVE_bsearch  /* bsearch() is broken in cygwin32 b18. */" >&4
+    echo "#undef  HAVE_h_errno  /* h_errno is broken in cygwin32 b18. */" >&4
+fi
+
+
 ### Test for correct toupper() and tolower()
 echo "Testing case conversion..."
 cat >test.c <<EOF
 #include <ctype.h>
 int main() { return !(toupper('a') == 'A'); }
 EOF
-if ${CC} ${CCFLAGS} test.c >/dev/null 2>&1 && ./a.out; then
+if ${CC} ${CCFLAGS} test.c >/dev/null 2>&1 && ./${AOUT}; then
     echo "Case conversion works."
     echo '#define CASE_OK' >&4
 else
@@ -639,7 +670,7 @@ else
 fi
 
 
-rm -f symtest.out a.out symtest.o symtest.c
+rm -f symtest.out ${AOUT} symtest.o symtest.c
 
 ### Library testing.
 # If libfoo.a make references to libbar.a, the order must be "-lfoo -lbar";
@@ -655,12 +686,12 @@ echo "Creating linker test..."
 echo 'main() { exit(0); }' > libtest.c
 ${CC} ${CCFLAGS} -c libtest.c >/dev/null 2>&1
 rm libtest.c
-LIBTEST="rm -f a.out; ${CC} ${CCFLAGS} libtest.o"
+LIBTEST="rm -f ${AOUT}; ${CC} ${CCFLAGS} libtest.o"
 
 ### Test LIBS, to make sure user didn't screw it up.
 
 if [ -n "$LIBS" ]; then
-    if eval "${LIBTEST} ${LIBS} >/dev/null" && test -f a.out; then
+    if eval "${LIBTEST} ${LIBS} >/dev/null" && test -f ${AOUT}; then
         : okay
     else
         echo
@@ -672,7 +703,7 @@ fi
 ### If -lbsd exists, we might need it (and it shouldn't make a difference if
 ### we don't need it, especially since it's the last library we link).
 
-if eval "${LIBTEST} -lbsd ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+if eval "${LIBTEST} -lbsd ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
     echo "Will link with -lbsd."
     LIBS="-lbsd $LIBS"
 fi
@@ -682,10 +713,10 @@ fi
 
 if egrep '^#define HAVE_gethostbyname$' ../src/config.h >/dev/null 2>&1; then
     : Already found it.
-elif eval "${LIBTEST} -lnsl_s ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+elif eval "${LIBTEST} -lnsl_s ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
     echo "Will link with -lnsl_s for gethostbyname()."
     LIBS="-lnsl_s $LIBS"
-elif eval "${LIBTEST} -lnsl ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+elif eval "${LIBTEST} -lnsl ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
     echo "Will link with -lnsl for gethostbyname()."
     LIBS="-lnsl $LIBS"
 else
@@ -697,14 +728,14 @@ fi
 ### If -linet exists, assume we need it.
 # note: -linet may require -lnsl (Dynix/ptx), so ordering is important.
 
-if eval "${LIBTEST} -linet ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+if eval "${LIBTEST} -linet ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
     echo "Will link with -linet."
     LIBS="-linet $LIBS"
 fi
 
 ### If -lnet exists, assume we need it.
 
-if eval "${LIBTEST} -lnet ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+if eval "${LIBTEST} -lnet ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
     echo "Will link with -lnet."
     LIBS="-lnet $LIBS"
 fi
@@ -713,7 +744,7 @@ fi
 ## Note: on IRIX 5, -lsocket exists, but we must not use its gethostbyname().
 if egrep '^#define HAVE_connect$' ../src/config.h >/dev/null 2>&1; then
     : Already found it.
-elif eval "${LIBTEST} -lsocket ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+elif eval "${LIBTEST} -lsocket ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
     echo "Will link with -lsocket for connect(), etc."
     echo "#define HAVE_connect" >&4
     LIBS="-lsocket $LIBS"
@@ -725,11 +756,11 @@ fi
 ### Test for SOCKS firewall proxy server.
 if [ -n "$SOCKS" ]; then
     # SOCKS uses res_init(), so we need -lresolv if there is one.
-    if eval "${LIBTEST} -lresolv ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+    if eval "${LIBTEST} -lresolv ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
         echo "Will link with -lresolv."
         LIBS="-lresolv $LIBS"
     fi
-    if eval "${LIBTEST} -lsocks ${LIBS} >/dev/null 2>&1" && test -f a.out; then
+    if eval "${LIBTEST} -lsocks ${LIBS} >/dev/null 2>&1" && test -f ${AOUT}; then
         echo "Will link with -lsocks."
         LIBS="-lsocks $LIBS"
         echo "#define SOCKS" >&4
@@ -738,7 +769,7 @@ if [ -n "$SOCKS" ]; then
         fi
     else
         echo "Can't find SOCKS library.  You may need to specify its location"
-        echo "  with an -L linker option in LIBS."
+        echo "  with an -L linker option in the LIBS line of unix/Config."
         exit 1
     fi
 fi
@@ -761,7 +792,7 @@ EOF
     else
         echo "strftime() not found.  Time formatting will not be supported."
     fi
-    rm -f test.c test.o a.out
+    rm -f test.c test.o ${AOUT}
 fi
 
 
@@ -785,7 +816,7 @@ EOF
     else
         echo "setlocale() not found.  Locales will not be supported."
     fi
-    rm -f test.c test.o a.out
+    rm -f test.c test.o ${AOUT}
 fi
 
 
@@ -795,55 +826,63 @@ fi
 
 ERR=">/dev/null 2>&1"
 
-if [ "$TERMINAL" != "HARDCODE" ]; then
+case "$TERMINAL" in
+HARDCODE*) # hardcode for a specific terminal
+  ;;
+*)         # use a termcap library
   if test -n "$TERMINAL" &&
-  eval "$LIBTEST -l$TERMINAL $LIBS $ERR" && test -f a.out; then
+  eval "$LIBTEST -l$TERMINAL $LIBS $ERR" && test -f ${AOUT}; then
     : okay
-  elif eval "$LIBTEST -ltermcap $LIBS $ERR" && test -f a.out; then
+  elif eval "$LIBTEST -ltermcap $LIBS $ERR" && test -f ${AOUT}; then
     TERMINAL=termcap
-  elif eval "$LIBTEST -lncurses $LIBS $ERR" && test -f a.out; then
+  elif eval "$LIBTEST -lncurses $LIBS $ERR" && test -f ${AOUT}; then
     TERMINAL=ncurses
-  elif eval "$LIBTEST -lcurses $LIBS $ERR" && test -f a.out; then
+  elif eval "$LIBTEST -lcurses $LIBS $ERR" && test -f ${AOUT}; then
     TERMINAL=curses
   else
     echo ''
-    echo "WARNING:  Can't link with ${TERMINAL-term library}.  Using HARDCODE."
-    echo "    TF will only work on a vt100 or similar terminal."
-    TERMINAL="HARDCODE"
+    echo "WARNING:  Can't link with ${TERMINAL-term library}."
+    TERMINAL="HARDCODE TERM_vt100"
     echo ''
   fi
   if [ "$TERMINAL" != "termcap" ] &&
     test -n "/usr/doc/debian*" && test -d /usr/i486-linuxaout/bin; then
     echo ''
     echo 'WARNING: this looks like Debian Linux without an ELF term library.'
-    echo 'Get one, or try setting PATH to "/usr/i486-linuxaout/bin:$PATH"'
+    echo 'Get one, or try prepending "/usr/i486-linuxaout/bin" to your PATH'
     echo 'before calling unixmake.'
     echo ''
   fi
-fi
-if [ "$TERMINAL" != "HARDCODE" ]; then
+  ;;
+esac
+
+case "$TERMINAL" in
+HARDCODE*)
+    echo "Will use hardcoded terminal codes: $TERMINAL"
+    echo "#define $TERMINAL" >&4
+    ;;
+*)
     echo "Will link with -l${TERMINAL}."
     LIBS="-l${TERMINAL} $LIBS"
     echo "#define TERMCAP" >&4
+    ;;
+esac
+
+
+if echo "$FLAGS" | egrep 'NO_FLOAT' >/dev/null 2>&1; then
+    echo "Floating point math disabled."
 else
-    echo "#define HARDCODE" >&4
+    LIBS="-lm $LIBS"
 fi
-
-
-#if [ -n "$USE_FLOAT" ]; then
-#    LIBS="-lm $LIBS"
-#    echo "#define USE_FLOAT" >&4
-#    echo "Floating point math enabled."
-#fi
 
 
 ### Figure out which terminal driver to use.
 
-if [ -z "$TTYDRIVER" ] && [ "$POSIX" = 1 ]; then
+if [ -z "$TTYDRIVER" ]; then
     if echo "#include <termios.h>" >test.c; ${CPP} test.c >/dev/null 2>&1; then
         TTYDRIVER="USE_TERMIOS"
         echo "Using <termios.h>."
-    else
+    elif [ "$POSIX" = 1 ]; then
         echo "Your system says it's POSIX, but I can't find <termios.h>.  Tsk."
     fi
 fi
@@ -910,7 +949,7 @@ echo >&5
 
 ### Clean up.
 
-rm -f test.c test.out test.o libtest.o a.out
+rm -f test.c test.out test.o libtest.o ${AOUT}
 
 ### Create ../src/Makefile.
 
