Import tf.33b4.tar.gz

diff --git a/src/autoconfig b/src/autoconfig
--- a/src/autoconfig
+++ b/src/autoconfig
@@ -1,7 +1,7 @@
 #!/bin/sh
 ########################################################################
 #  TinyFugue - programmable mud client
-#  Copyright (C) 1993  Ken Keys
+#  Copyright (C) 1994 Ken Keys
 #
 #  TinyFugue (aka "tf") is protected under the terms of the GNU
 #  General Public License.  See the file "COPYING" for details.
@@ -12,7 +12,7 @@
 
 #
 # TinyFugue autoconfiguration
-# Descriptor 3 is mf.vars, descriptor 4 is config.h.
+# Descriptor 4 is config.h, descriptor 5 is mf.vars.
 # 
 
 ### A few portability notes.
@@ -21,7 +21,6 @@
 # Some versions of 'test' have the wrong precedence for unary operators,
 #   so we use the shell's '&&' and '||' operators instead of '-a' and '-o'.
 # 4.3 BSD 'test' does not have '-x'.  Use '-f' or '-r' instead.
-# Bash (sh replacement on linux) doesn't like exec for i/o redirection (?).
 
 ### Some notes on predefined preprocessor identifiers.
 # M_UNIX	SCO UNIX
@@ -29,6 +28,8 @@
 # sequent	Dynix
 # _SEQUENT_	Dynix/ptx
 
+
+rm -f Makefile
 
 ### Initialize variables, just in case they're already defined.
 
@@ -50,8 +51,7 @@ MANPAGE=''
 MANTYPE='cat'
 POSIX=0
 QUIET=''
-RAND=''
-REGEXP_ERR='/dev/null'
+REGEXP_ERR='&1'
 STRIP='strip'
 SYMLINK=''
 SYSTEM=''
@@ -67,12 +67,10 @@ if [ -r ../Config ]; then . ../Config; fi
 ### editing the default version.
 if [ -r ../dev/config ]; then . ../dev/config; fi
 
-rm -f Makefile
-
-echo '#### variables generated by autoconfig' >&3
-echo >&3
-echo "TFVERSION  = \"${TFVERSION}\"" >&3
-echo "UNAME      = \"`{ uname -a ; } 2>/dev/null`\"" >&3
+echo '#### variables generated by autoconfig' >&5
+echo >&5
+echo "TFVERSION  = \"${TFVERSION}\"" >&5
+echo "UNAME      = \"`{ uname -a ; } 2>/dev/null`\"" >&5
 
 cat >&4 <<EOF
 /* config.h
@@ -80,9 +78,12 @@ cat >&4 <<EOF
  */
 EOF
 
+echo "Configuring $TFVERSION"
+echo
+
 if [ -z "$QUIET" ] && echo $TFVERSION | egrep "alpha" >/dev/null 2>&1; then
 cat <<EOF
-Note:  This is an alpha version, and so it has not been fully tested.
+This is an alpha version, and so may not be fully tested on some platforms.
 With the new features comes the possibility of new bugs.  If you don't want
 to deal with this, get the latest beta version.
 
@@ -91,21 +92,19 @@ fi
 
 if [ -z "$QUIET" ]; then
 cat <<EOF
-TinyFugue is the result of several years of voluntary work.  If you use
-it, please send a donation to the author.  A reasonable amount might be
-\$10, but send whatever you think is appropriate.  Your donation will
-cover the past time and effort put into TinyFugue, as well as user
-support, maintenance, and future versions.  Be sure to include your
-name and email address with your donation sent to:
+TinyFugue is the result of several years of voluntary work.  If you use it,
+please send a donation to the author.  A reasonable amount might be \$10, but
+send whatever you think is appropriate.  Your donation will cover past time and
+effort put into TF, as well as user support, maintenance, and future versions.
+Be sure to include your name and email address with your donation sent to:
 
   Ken Keys
   1820 Cottonwood Ave.
   Carlsbad, CA 92009
+  USA
 
 EOF
 fi
-
-echo "Configuring $TFVERSION"
 
 
 ### Figure out installation locations.
@@ -142,11 +141,19 @@ then
    exit 2
 fi
 
-if echo "$EXE"       | egrep "^`pwd`/" >/dev/null 2>&1 ||
-   echo "$LIBDIR"    | egrep "^`pwd`/" >/dev/null 2>&1 ||
-   echo "$SYMLINK"   | egrep "^`pwd`/" >/dev/null 2>&1
+# Don't allow installation in the build tree (people have actually tried this).
+# The cd;pwd is needed to normalize the directory name in case of links.
+DIR1=`cd \`echo $EXE     | sed 's;/[^/]*$;;'\`; pwd`
+DIR2=`cd \`echo $LIBDIR  | sed 's;/[^/]*$;;'\`; pwd`
+DIR3=`cd \`echo $SYMLINK | sed 's;/[^/]*$;;'\`; pwd`
+BUILDTREE=`cd ..; pwd`
+if echo "${DIR1}/" | egrep "^${BUILDTREE}/" >/dev/null 2>&1 ||
+   echo "${DIR2}/" | egrep "^${BUILDTREE}/" >/dev/null 2>&1 ||
+   echo "${DIR3}/" | egrep "^${BUILDTREE}/" >/dev/null 2>&1
 then
-    echo "You should not install files in `pwd`."
+    echo
+    echo "You can not install files in the build tree,"
+    echo "${BUILDTREE}."
     echo "Edit Config and try again."
     exit 2
 fi
@@ -171,16 +178,16 @@ if [ -z "$MAILDIR" ]; then
 fi
 
 
-echo "EXE        = ${EXE}" >&3
-echo "SYMLINK    = ${SYMLINK}" >&3
-echo "LIBDIR     = ${LIBDIR}" >&3
-echo "TFLIBRARY  = ${LIBDIR}/stdlib.tf" >&3
-echo "HELPFILE   = ${LIBDIR}/tf.help" >&3
-echo "MANPAGE    = ${MANPAGE}" >&3
-echo "MANTYPE    = ${MANTYPE}" >&3
-echo "MAILDIR    = ${MAILDIR}" >&3
-echo "MAKE       = ${MAKE}" >&3
-echo "MODE       = ${MODE}" >&3
+echo "EXE        = ${EXE}" >&5
+echo "SYMLINK    = ${SYMLINK}" >&5
+echo "LIBDIR     = ${LIBDIR}" >&5
+echo "TFLIBRARY  = ${LIBDIR}/stdlib.tf" >&5
+echo "HELPFILE   = ${LIBDIR}/tf.help" >&5
+echo "MANPAGE    = ${MANPAGE}" >&5
+echo "MANTYPE    = ${MANTYPE}" >&5
+echo "MAILDIR    = ${MAILDIR}" >&5
+echo "MAKE       = ${MAKE}" >&5
+echo "MODE       = ${MODE}" >&5
 
 echo "#define LIBDIR     \"${LIBDIR}\"" >&4
 echo "#define TFLIBRARY  \"${LIBDIR}/stdlib.tf\"" >&4
@@ -190,16 +197,15 @@ echo "#define MAILDIR    \"${MAILDIR}\"" >&4
 
 ### Confirm.
 
-echo
 echo "TF binary will be installed in     $EXE"
 if [ -n "$SYMLINK" ]; then
     echo "    with a symbolic link in        $SYMLINK"
 fi
 echo "Library, help, and utilities:      ${LIBDIR}/"
 if [ -n "$MAILDIR" ]; then
-    echo "Mail will be checked in directory  ${MAILDIR}/"
+    echo "Default mail directory:           ${MAILDIR}/"
 else
-    echo "Mail directory unknown.  TF may not be able to check mail."
+    echo "Mail directory unknown.  TF will not check mail if MAIL is unset."
 fi
 if [ -n "$MANPAGE" ]; then
     echo "Man page will be installed in      $MANPAGE in $MANTYPE format"
@@ -214,7 +220,8 @@ while [ -z "$ans" ]; do
     read ans;
     case "$ans" in
     y|Y)  break ;;
-    n|N)  exit 1 ;;
+    n|N)  rm -f Makefile config.h
+          exit 1 ;;
     *)    ans=
           echo 'Please answer "y" or "n".'
           ;;
@@ -229,18 +236,19 @@ if [ -z "$QUIET" ]; then
     LIB=`echo $LIBDIR | sed 's;/[^/]*$;;'`
     old="`ls -d $EXE $BINDIR/tf*connect $LIB/tf*lib* $LIB/tf*help* 2>/dev/null`"
     if [ -n "$old" ]; then
-        echo "I noticed you have some files from previous versions:"
+        echo "I noticed you have some old tf files:"
         echo "$old"
         ans=
         while [ -z "$ans" ]; do
             echo 'Do you want those files removed? (y/n)'
             read ans;
             case "$ans" in
-            n|N)  echo "Files not removed."
+            n|N)  echo "Old files will not be removed."
                   break
                   ;;
-            y|Y)  echo "Files will be removed before new ones are installed."
-                  echo OBSOLETE = ${old} >&3
+            y|Y)  echo "Old files will be removed before installing new ones."
+                  # NO QUOTES in the next line; we don't want newlines.
+                  echo OBSOLETE = ${old} >&5
                   ;;
             *)    ans=
                   echo 'Please answer "y" or "n".'
@@ -262,14 +270,13 @@ fi
 if [ -z "$CC" ]; then
     if { gcc -v; } > /dev/null 2>&1; then
         CC='gcc'
-        GNU_C=1
     else
         CC='cc'
     fi
 fi
 
 echo "Will compile with: ${CC} ${CCFLAGS}"
-echo "CC         = ${CC}" >&3
+echo "CC         = ${CC}" >&5
 
 ### Figure out how to run preprocessor.
 # Most compilers have an -E flag to run the preprocessor only.
@@ -337,6 +344,7 @@ if ${CPP} ${CCFLAGS} test.c > test.out 2>/dev/null; then
         POSIX=0
     fi
 else
+    echo "/* #define HAVE_UNISTD_H */" >&4
     echo "I can't find unistd.h.  The compiler may produce a lot of"
     echo "warnings, but you can probably ignore them."
     echo "This doesn't appear to be a POSIX system."
@@ -356,6 +364,7 @@ if echo "#include <stdlib.h>" >test.c; ${CPP} test.c >/dev/null 2>&1; then
     echo "#define HAVE_STDLIB_H" >&4
     echo "Found <stdlib.h>."
 else
+    echo "/* #define HAVE_STDLIB_H */" >&4
     echo "I can't find <stdlib.h>.  The compiler may produce a lot of"
     echo "    warnings, but you can probably ignore them."
 fi
@@ -371,7 +380,10 @@ if [ "$ANSI_C" = "1" ] || [ "$GNU_C" = "1" ]; then
         echo "Your compiler says it's ANSI, but <stdarg.h> fails.  Tsk tsk."
         echo "    I'm going to undefine __STDC__.  Cross your fingers."
         echo "#undef __STDC__" >&4
+        echo "/* #define HAVE_STDARG */" >&4
     fi
+else
+    echo "/* #define HAVE_STDARG */" >&4
 fi
 
 ### Figure out which string header to include.
@@ -390,6 +402,8 @@ fi
 if echo "#include <memory.h>" >test.c; ${CPP} test.c >/dev/null 2>&1; then
     echo "#define HAVE_MEMORY_H" >&4
     echo "Found <memory.h>."
+else
+    echo "/* #define HAVE_MEMORY_H */" >&4
 fi
 
 
@@ -422,6 +436,7 @@ ${CPP} test.c >/dev/null 2>&1; then
 else
     echo "I can't find <netinet/in.h>, <sys/in.h>, or <sys/netinet/in.h>."
     echo "Good luck."
+    echo "/* #define HAVE_NETINET_IN_H */" >&4
 fi
 
 ### Find internet headers
@@ -432,6 +447,7 @@ elif echo "#include <sys/inet.h>" >test.c; ${CPP} test.c >/dev/null 2>&1; then
     echo "#define HAVE_SYS_INET_H" >&4
     echo "Found <sys/inet.h>."
 else
+    echo "/* #define HAVE_ARPA_INET_H */" >&4
     echo "I can't find <arpa/inet.h> or <sys/inet.h>, but we should be okay."
 fi
 
@@ -497,8 +513,12 @@ rm libtest.c
 if [ -z "$LIBC" ] || [ ! -f "$LIBC" ]; then
     if [ -r /lib/libc.a ]; then
         LIBC='/lib/libc.a'
+    elif [ -r /lib/libc_s.a ]; then
+        LIBC='/lib/libc_s.a'
     elif [ -r /usr/lib/libc.a ]; then
         LIBC='/usr/lib/libc.a'
+    elif [ -r /usr/lib/libc_s.a ]; then
+        LIBC='/usr/lib/libc_s.a'
     elif [ -r /usr/ccs/lib/libc.a ]; then
         LIBC='/usr/ccs/lib/libc.a'
     elif [ -r /usr/lib/libNeXT_s.a ]; then
@@ -510,7 +530,7 @@ fi
 
 if [ -n "$LIBC" ]; then
     echo "Examining ${LIBC}..."
-    { nm $LIBC; } >libc.test 2>/dev/null
+    { nm $LIBC; } >libc.list 2>/dev/null
     if [ ! -s libc.list ]; then ar t $LIBC >libc.list 2>/dev/null; fi
 else
     echo "I can't read your C library!"
@@ -519,23 +539,25 @@ else
 fi
 
 ### Look for rand() or random().
-### rand() is ANSI, but random() is more random.
 
-if [ -z "$RAND" ]; then
-    if egrep '(^|[^a-z])random([^a-z]|$)' libc.list >/dev/null 2>&1; then
-        echo "Found random() in your C library."
-        echo "#define RANDOM  random" >&4
-        echo "#define SRANDOM srandom" >&4
-    elif egrep '(^|[^a-z])rand([^a-z]|$)' libc.list >/dev/null 2>&1; then
-        echo "Found rand() in your C library."
-        echo "#define RANDOM  rand" >&4
-        echo "#define SRANDOM srand" >&4
-    else
-        echo "#define RANDOM  rand" >&4
-        echo "#define SRANDOM srand" >&4
-        echo "I can't find rand() or random().  I'll assume you have"
-        echo "    rand().  If not, edit the RAND line in the Config file."
-    fi
+if egrep '(^|[^a-z])srandom([^a-z]|$)' libc.list >/dev/null 2>&1; then
+    echo "#define HAVE_RANDOM" >&4
+    echo "Found random() in your C library."
+elif egrep '(^|[^a-z])srand([^a-z]|$)' libc.list >/dev/null 2>&1; then
+    echo "#define HAVE_RAND" >&4
+    echo "Found rand() in your C library."
+else
+    echo "/* #define HAVE_RAND */" >&4
+    echo "I can't find rand() or random().  Assuming you have rand()."
+fi
+
+### Look for bsearch().
+if egrep '(^|[^a-z])bsearch([^a-z]|$)' libc.list >/dev/null 2>&1; then
+    echo "Found bsearch() in your C library."
+    echo "#define HAVE_BSEARCH" >&4
+else
+    echo "I can't find bsearch().  That's okay, I'll use my own."
+    echo "/* #define HAVE_BSEARCH */" >&4
 fi
 
 ### See if getcwd(), getwd(), or neither is available.  This isn't vital.
@@ -548,6 +570,7 @@ elif egrep '(^|[^a-z])getwd([^a-z]|$)' libc.list >/dev/null 2>&1; then
     echo "#define HAVE_GETWD" >&4
 else
     echo "I can't find getwd() or getcwd().  No big deal."
+    echo "/* #define HAVE_GETCWD */" >&4
 fi
 
 ### Look for memcpy() or bcpy().
@@ -557,14 +580,11 @@ if egrep '(^|[^a-z])memcpy([^a-z]|$)' libc.list >/dev/null 2>&1; then
     echo "#define HAVE_MEMCPY" >&4
 elif egrep '(^|[^a-z])bcpy([^a-z]|$)' libc.list >/dev/null 2>&1; then
     echo "Found bcpy() in your C library."
-    echo "#define HAVE_BCPY" >&4
+    echo "#define HAVE_BCOPY" >&4
 else
-    echo "I can't find memcpy() or bcpy().  Good luck."
-    if [ "$ANSI_C" = "1" ]; then
-        echo "    Since this is ANSI, I'll assume you have memcpy()."
-    else
-        echo "    I'll assume you have bcpy()."
-    fi
+    echo "I can't find memcpy() or bcopy().  Good luck."
+    echo "    I'll assume you have memcpy()."
+    echo "/* #define HAVE_MEMCPY */" >&4
 fi
 
 ### Look for strchr() or index().
@@ -577,11 +597,8 @@ elif egrep '(^|[^a-z])index([^a-z]|$)' libc.list >/dev/null 2>&1; then
     echo "#define HAVE_INDEX" >&4
 else
     echo "I can't find strchr() or index().  Good luck."
-    if [ "$ANSI_C" = "1" ]; then
-        echo "    Since this is ANSI, I'll assume you have strchr()."
-    else
-        echo "    I'll assume you have index()."
-    fi
+    echo "    I'll assume you have strchr()."
+    echo "/* #define HAVE_STRCHR */" >&4
 fi
 
 ### Look for strstr().
@@ -591,6 +608,7 @@ if egrep '(^|[^a-z])strstr([^a-z]|$)' libc.list >/dev/null 2>&1; then
     echo "#define HAVE_STRSTR" >&4
 else
     echo "I can't find strstr().  That's okay, I'll use my own."
+    echo "/* #define HAVE_STRSTR */" >&4
 fi
 
 ### Look for strtol().
@@ -600,6 +618,7 @@ if egrep '(^|[^a-z])strtol([^a-z]|$)' libc.list >/dev/null 2>&1; then
     echo "#define HAVE_STRTOL" >&4
 else
     echo "I can't find strtol().  That's okay, I'll use my own."
+    echo "/* #define HAVE_STRTOL */" >&4
 fi
 
 ### Look for strftime().
@@ -614,6 +633,7 @@ elif ${CC} ${CCFLAGS} -lintl libtest.o >/dev/null 2>&1; then
     LIBS="$LIBS -lintl"
 else
     echo "I can't find strftime().  time_format will not be supported."
+    echo "/* #define HAVE_STRFTIME */" >&4
 fi
 
 
@@ -623,6 +643,14 @@ fi
 # So we test incrementally, building the list from right to left.
 # For Dynix/ptx, order must be: -lsocket -linet -lnsl
 # For SysV, -lsocket test needs -lnsl.
+
+### If -lbsd exists, we might need it (and it shouldn't make a difference if
+### we don't need it).
+
+if ${CC} ${CCFLAGS} libtest.o -lbsd ${LIBS} >/dev/null 2>&1; then
+    echo "Will link with -lbsd."
+    LIBS="-lbsd $LIBS"
+fi
 
 ### If gethostbyname() isn't in libc, look for -lnsl_s, -lnsl, or -lresolv.
 # note: can't assume existance of libs implies need; must check libc first. (?)
@@ -638,6 +666,9 @@ elif ${CC} ${CCFLAGS} libtest.o -lnsl ${LIBS} >/dev/null 2>&1; then
 elif ${CC} ${CCFLAGS} libtest.o -lresolv ${LIBS} >/dev/null 2>&1; then
     echo "Will link with -lresolv."
     LIBS="-lresolv $LIBS"
+else
+    echo "Warning: can't find gethostbyname() or a library that might have it."
+    echo "/* warning: autoconfig couldn't find gethostbyname() */" >&4
 fi
 
 ### If -linet exists, assume we need it.
@@ -655,7 +686,7 @@ if ${CC} ${CCFLAGS} libtest.o -lnet ${LIBS} >/dev/null 2>&1; then
     LIBS="-lnet $LIBS"
 fi
 
-### If -lsocket exists, assume we need it (for getsockopt() and getpeername()).
+## If -lsocket exists, assume we need it (for socket(), connect(), etc)
 if ${CC} ${CCFLAGS} libtest.o -lsocket ${LIBS} >/dev/null 2>&1; then
     echo "Will link with -lsocket."
     LIBS="-lsocket $LIBS"
@@ -665,13 +696,13 @@ fi
 ### test termcap.
 
 if [ "$TERMINAL" = "TERMCAP" ]; then
-    if ${CC} ${CCFLAGS} -ltermcap libtest.o >/dev/null 2>&1; then
+    if ${CC} ${CCFLAGS} libtest.o -ltermcap ${LIBS} >/dev/null 2>&1; then
         echo "Will link with -ltermcap."
-        LIBS="$LIBS -ltermcap"
+        LIBS="-ltermcap $LIBS"
     else
         echo "WARNING:  Can't link with -ltermcap.  Using HARDCODE instead."
         echo "    TF will only work on a vt100 or similar terminal."
-        TERMINAL="-DHARDCODE"
+        TERMINAL="HARDCODE"
     fi
 fi
 echo "#define $TERMINAL" >&4
@@ -699,6 +730,7 @@ if [ -z "$TTYDRIVER" ]; then
 
     if [ "$HAVE_TERMIO" = 1 ] && [ "$HAVE_SGTTY" = 1 ]; then
         echo "Your system has both <termio.h> and <sgtty.h>..."
+#       They should both work, but let's try to use the "native" driver.
 #       Make a semi-educated guess, and warn the user.
 #       Many USG systems have uname, many BSD systems don't.
         if { uname; } >/dev/null 2>&1; then
@@ -728,7 +760,7 @@ FLAGS="$CCFLAGS $FLAGS"
 
 OBJS="command.o dstring.o expand.o help.o history.o keyboard.o \
 macro.o main.o malloc.o output.o process.o search.o signals.o socket.o \
-special.o tfio.o tty.o util.o variable.o world.o regexp/regexp.o"
+tfio.o tty.o util.o variable.o world.o regexp/regexp.o"
 
 if [ -n "$DMALLOC" ]; then
     FLAGS="$FLAGS -DDMALLOC"
@@ -737,12 +769,12 @@ fi
 
 ### write variables
 
-echo "STRIP      = $STRIP" >&3
-echo "FLAGS      = $FLAGS" >&3
-echo "LIBS       = $LIBS" >&3
-echo "OBJS       = $OBJS" >&3
-echo "REGEXP_ERR = $REGEXP_ERR" >&3
-echo >&3
+echo "STRIP      = $STRIP" >&5
+echo "FLAGS      = $FLAGS" >&5
+echo "LIBS       = $LIBS" >&5
+echo "OBJS       = $OBJS" >&5
+echo "REGEXP_ERR = $REGEXP_ERR" >&5
+echo >&5
 
 ### Clean up.
 
@@ -751,13 +783,10 @@ rm -f test.c test.out test.o a.out libc.list
 ### Create Makefile.
 
 cat > Makefile <<EOF
-#### This Makefile was automaticaly generated by src/autoconfig.
-#### You can run it directly, or use the Makefile in the top directory.
-#### To make a minor change without running autoconfig (or the top Makefile)
-#### again, you can edit the variables below; but, if you do run the top
-#### Makefile again, any changes you made to this Makefile may be lost.
-#### For a permanant configuration change, edit Config and run the top
-#### Makefile again.
+#### This src/Makefile was automatically generated by src/autoconfig.
+#### The recommended precedure is to run the Makefile in the top directory.
+#### You should not edit this file -- all configuration changes should
+#### be made to the Config file in the top directory.
 
 EOF
 
